services:
  api-router:
    image: nginx:alpine
    ports:
      - "3000:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app-prod
      - api-prod
    networks:
      - portfolio-chat
    restart: unless-stopped

  app-prod:
    image: ghcr.io/voncerbau/portfolio-chat-front:v0.1
    environment:
      - VITE_API_DATA_URL=http://localhost:3000/api
      - VITE_CONNECT_ATTEMPTS=5
      - PRODUCTION_PORT=3300
    networks:
      - portfolio-chat
    depends_on:
      - api-prod
    restart: unless-stopped

  api-prod:
    image: ghcr.io/voncerbau/portfolio-chat-back:v0.1
    environment:
      - MONGODB_URI=mongodb://mongoadmin:mongopass@api-data:27017/full-chat-db?authSource=admin
    networks:
      - portfolio-chat
    depends_on:
      - api-data
    restart: unless-stopped

  api-data:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=mongopass
      - MONGO_INITDB_DATABASE=full-chat-db
    networks:
      - portfolio-chat
    restart: unless-stopped

networks:
  portfolio-chat:
    driver: bridge
