services:
  app-dev:
    image: ghcr.io/voncerbau/portfolio-chat-front:v0.1
    environment:
      - API_DATA_URL=http://api-dev:${BACK_END_PORT}
    ports:
      - ${FRONT_END_PORT}:${FRONT_END_PORT}
    networks:
      - portfolio-chat
    depends_on:
      - api-dev
    restart: unless-stopped

  api-dev:
    image: ghcr.io/voncerbau/full-stack-chat-back:v0.1
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=api-data
      - DB_PORT=${DB_PORT}
      - CORS_ORIGIN=http://app-dev:${FRONT_END_PORT}
    ports:
      - ${BACK_END_PORT}:${BACK_END_PORT}
    networks:
      - portfolio-chat
    depends_on:
      - api-data
    restart: unless-stopped

  api-data:
    image: ghcr.io/voncerbau/full-stack-chat-data:v0.1
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - portfolio-chat
    restart: unless-stopped

networks:
  portfolio-chat:
    driver: bridge
